### ISSUE TITLE
Support for logic operators

### ISSUE THREAD

**Issue by fsaintjacques** [ThePhD/itsy_bitsy#2]
Do you plan to support logical operator (`&`, `|`, `^` and `~`) in both the [assign](https://en.cppreference.com/w/cpp/utility/bitset/operator_logic) and non-member [function](https://en.cppreference.com/w/cpp/utility/bitset/operator_logic2) form?

**Comment by fsaintjacques** [comment]
@ThePhD gentle ping.

**Comment by ThePhD** [comment]
... How do I always miss the issue requests for this repository?

Yes, that's on the menu. I'll try to get to it this week.

**Comment by jeb2239** [comment]
@ThePhD Is this being worked on or can I give it a shot?

**Comment by ThePhD** [comment]
@jeb2239 I was going to, but you can absolutely! Piles of work, so I'd absolutely appreciate any contributions.

**Comment by jeb2239** [comment]
Is there a certain style I should adhere to, naming convention, things to keep in mind, or other things I should read? If not then I will just try my best to infer the style from what is there and from libstdc++. I read your gsoc proposal (it's great!). I also looked at the tr2 dynamic bitset but that is about it.

**Comment by ThePhD** [comment]
There [is a `.clang-format` file](https://github.com/ThePhD/itsy_bitsy/blob/master/.clang-format) that will aid in automatically formatting your code when you make changes. Everything should be  -- at least to some degree -- be consistent with that. If the formatter goes hog wild on a file and changes things, that's okay: I think at one point I shifted from doing it the way libstdc++ does things to keep something that is just for this repository!

**Comment by ThePhD** [comment]
You can use clang-format as a standalone command line tool or as part of your favorite editor/IDE: https://clang.llvm.org/docs/ClangFormat.html

**Comment by ThePhD** [comment]
This took forever, SHEESH. But the implementation - and a bunch of other fixes - are done. Sorry about that!!
